### PR TITLE
Fix hal-sleep-manager test on nRF52 and clean it up in general

### LINKED ISSUE #73: hal-sleep-manager test failing on nRF52
This test is failing due to another interrupt waking up the core while it's supposed to be deep sleeping.  Verified this by disabling all interrupts other than RTC1 -- the test now passes.

Additionally, the test has some very poorly set up checks that were masking this issue behind another message -- "core did not enter deep sleep".  The test was only checking the ratios of time elapsed on the lp and us tickers, not the actual times, so when both times were very close to zero, the the test would intermittently fail.

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 

This PR fixes #73 , and cleans up the hal-sleep-manager test in general.  The main issue was that UART transmissions (from the test framework) were generating interrupts that were waking the processor out of sleep.  This caused the test to end up sleeping for only 1-2 lp ticks instead of the ~600 ticks intended.  However, a secondary issue was that the test was not checking the actual time slept, just the ratio between us ticks and lp ticks.  This meant that it was trying to compare ratios between durations near zero when this issue would happen, making it crapshoot whether or not the test would "pass."

To fix these issues, I added a new sleep call and changed how the assertions in the test are set up.

#### Impact of changes 
hal-sleep-manager should now pass for nRF52

#### Migration actions required 
None

### Documentation 

None
----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [X] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

@JohnK1987 
@jay-sridharan 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

File: hal/tests/TESTS/mbed_hal/sleep_manager/main.cpp [hunk 1]
```diff
@@ -143,18 +144,25 @@ void test_sleep_auto()
     const ticker_irq_handler_type lp_ticker_irq_handler_org = set_lp_ticker_irq_handler(lp_ticker_isr);
     uint32_t us_ts1, us_ts2, lp_ts1, lp_ts2, us_diff1, us_diff2, lp_diff1, lp_diff2;
 
-    /*  Let's avoid the Lp ticker wrap-around case */
```
Comment (multiplemonomials) [inline hal/tests/TESTS/mbed_hal/sleep_manager/main.cpp:146]: I moved this block down after the sleep_manager_can_deep_sleep_test_check() call, because that call can end up waiting for a long time which could interfere with the test.

File: hal/tests/TESTS/mbed_hal/sleep_manager/main.cpp [hunk 2]
```diff
@@ -163,23 +171,25 @@ void test_sleep_auto()
     us_ts2 = us_ticker_read();
     lp_ts2 = lp_ticker_read();
 
-    us_diff1 = ticks_to_us((us_ts1 <= us_ts2) ? (us_ts2 - us_ts1) : (us_ticker_mask - us_ts1 + us_ts2 + 1), us_ticker_info->frequency);
-    lp_diff1 = ticks_to_us((lp_ts1 <= lp_ts2) ? (lp_ts2 - lp_ts1) : (lp_ticker_mask - lp_ts1 + lp_ts2 + 1), lp_ticker_info->frequency);
+    us_diff1 = (us_ts1 <= us_ts2) ? (us_ts2 - us_ts1) : (us_ticker_mask - us_ts1 + us_ts2 + 1);
```
Comment (multiplemonomials) [inline hal/tests/TESTS/mbed_hal/sleep_manager/main.cpp:174]: Changed these variables to be in ticks instead of microseconds for better precision

**Review by JohnK1987 — APPROVED** [review]

File: hal/tests/TESTS/mbed_hal/sleep_manager/main.cpp (hunk 2 above)
Comment (JohnK1987) [reply hal/tests/TESTS/mbed_hal/sleep_manager/main.cpp:174]: sound logic, lets try

**Comment by multiplemonomials** [comment]
Test results look good:
```
95% tests passed, 4 tests failed out of 73

Total Test time (real) = 973.42 sec

The following tests did not run:
	  8 - mbed-hal-crc (Skipped)
	 13 - mbed-hal-mpu (Skipped)
	 14 - mbed-hal-ospi (Skipped)
	 16 - mbed-hal-qspi (Skipped)
	 17 - mbed-hal-reset-reason (Skipped)
	 18 - mbed-hal-rtc (Skipped)
	 19 - mbed-hal-rtc-reset (Skipped)
	 20 - mbed-hal-rtc-time (Skipped)
	 21 - mbed-hal-rtc-time-conv (Skipped)
	 29 - mbed-hal-watchdog (Skipped)
	 30 - mbed-hal-watchdog-reset (Skipped)
	 31 - mbed-hal-watchdog-timing (Skipped)
	 32 - mbed-hal-verify-arduino-pinmap (Skipped)
	 43 - mbed-platform-crash-reporting (Skipped)
	 53 - mbed-platform-stats-cpu (Skipped)
	 54 - mbed-platform-stats-heap (Skipped)
	 55 - mbed-platform-stats-sys (Skipped)
	 56 - mbed-platform-stats-thread (Skipped)
	 71 - mbed-connectivity-nfc-eeprom (Skipped)
	 73 - mbed-connectivity-ble-cordio-hci-transport (Skipped)

The following tests FAILED:
	  2 - mbed-usb-device-basic (Failed)
	  3 - mbed-usb-device-hid (Failed)
	  5 - mbed-usb-device-serial (Failed)
	 61 - mbed-rtos-kernel-tick-count (Failed)
```
